backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}{{second}}"
    identifier_field: "body"
    summary: "{{body}}"
    fields:
      - { label: "Categories", name: "categories", widget: "list", required: false, hint: "Enter categories or tags for this article." }
      - { label: "Body", name: "body", widget: "markdown" }
