backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "hidden", required: false }
      - { label: "Publish Date", name: "date", widget: "hidden", required: false }
      - { label: "Author", name: "author", widget: "hidden", required: false }
      - { label: "Cover Image", name: "cover", widget: "hidden", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "hidden", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
